
id = "d30ccaa1-c764-454b-9389-7507bfe0fcbe"
name     = "Door Opened - Laundry Room"
enabled  = false
priority = 10

[trigger]
type      = "device_state_changed"
device_id = "yolink_d88b4c0200142e3c"
attribute = "open"
to        = true

[[actions]]
type      = "set_device_state"
device_id = "lutron_54"
state     = { on = true }

[[actions]]
type      = "set_device_state"
device_id = "timer_garage_lights"
state     = { command = "start", duration_secs = 600, label = "Garage Lights Off" }
