
id = "597f80ec-4159-4ff1-a6f1-5b0c5dcd5f6f"
name     = "Door Opened - Garage Deck"
enabled  = false
priority = 10

[trigger]
type      = "device_state_changed"
device_id = "yolink_d88b4c01000e82eb"
attribute = "open"
to        = true

[[actions]]
type      = "set_device_state"
device_id = "switch_any_deck_door_open"
state     = { on = true }

[[actions]]
type = "conditional"
condition = "device_state(\"mode_night\")[\"on\"] == true"
then_actions = [
  { type = "set_device_state", device_id = "timer_deck_lights_off", state = { command = "cancel" } },
  { type = "set_device_state", device_id = "lutron_scene_deck_on_phantom", state = { activate = true } },
]
