
id = "40469bde-5042-4d4a-bc28-e62c8244b444"
name     = "Any Deck Door Opened"
enabled  = true
priority = 10

[trigger]
type      = "device_state_changed"
device_id = "switch_any_deck_door_open"
attribute = "on"
to        = false

[[conditions]]
type      = "device_state"
device_id = "mode_night"
attribute = "on"
op        = "eq"
value     = true

[[actions]]
type      = "set_device_state"
device_id = "timer_deck_lights_off"

[actions.state]
command       = "start"
duration_secs = 300
