# Bathroom - Door Opens
#
# When the bathroom door opens: stop the Sonos and start a 5-minute countdown.
# The timer firing will turn off the exhaust fan.
# Why is hot-reload not working
#
id = "d12062ac-32f8-41c5-9dab-38adc0de6dd0"
name     = "Door Opened - Bathroom"
enabled  = true
priority = 10

[trigger]
type      = "device_state_changed"
device_id = "yolink_d88b4c0400064299"
attribute = "open"
to        = true

[[actions]]
type      = "set_device_state"
device_id = "sonos_bathroom"
state     = { action = "stop"}

[[actions]]
type      = "set_device_state"
device_id = "timer_bathroom"

[actions.state]
command       = "start"
duration_secs = 300
