id = "4ad53081-5c15-465b-8d31-5ec97b289d12"
name = "All Deck Doors Closed — Start Lights Timer"
enabled = true
priority = 20
tags = []
log_events = false
log_triggers = false
log_actions = false
cancel_on_false = false

[trigger]
type = "device_state_changed"
device_id = "yolink_d88b4c01000e813f"
device_ids = [
    "yolink_d88b4c01000e8304",
    "yolink_d88b4c01000e82eb",
    "yolink_d88b4c0200142eb8",
]
attribute = "open"
to = false

[[conditions]]
type = "device_state"
device_id = "yolink_d88b4c01000e813f"
attribute = "open"
op = "eq"
value = false

[[conditions]]
type = "device_state"
device_id = "yolink_d88b4c01000e8304"
attribute = "open"
op = "eq"
value = false

[[conditions]]
type = "device_state"
device_id = "yolink_d88b4c01000e82eb"
attribute = "open"
op = "eq"
value = false

[[conditions]]
type = "device_state"
device_id = "yolink_d88b4c0200142eb8"
attribute = "open"
op = "eq"
value = false

[[actions]]
enabled = true
type = "conditional"
condition = 'device_state("mode_night")["on"] == true'
else_actions = []

[[actions.then_actions]]
type = "set_device_state"
device_id = "timer_deck_lights_off"
track_event_value = false

[actions.then_actions.state]
command = "start"
duration_secs = 300
label = "Deck lights off"
