id = "d30ccaa1-c764-454b-9389-7507bfe0fcbe"
name = "Door Opened - Laundry Room"
enabled = true
priority = 10
tags = []
conditions = []
log_events = false
log_triggers = false
log_actions = false
cancel_on_false = false

[trigger]
type = "device_state_changed"
device_id = "yolink_d88b4c0200142e3c"
attribute = "open"
to = true

[[actions]]
enabled = true
type = "set_device_state"
device_id = "lutron_54"
track_event_value = false

[actions.state]
on = true

[[actions]]
enabled = true
type = "set_device_state"
device_id = "timer_garage_lights"
track_event_value = false

[actions.state]
command = "start"
duration_secs = 600
label = "Garage Lights Off"
