id = "ea75205d-22fe-4e5b-a1c0-65eb24ce54a6"
name     = "Deck Lights Off - Timer Finished"
enabled  = true
priority = 10

[trigger]
type      = "device_state_changed"
device_id = "timer_deck_lights_off"
attribute = "state"
to        = "finished"

[[actions]]
type = "set_device_state"
device_id = "lutron_scene_deck_off_phantom"
state = { activate = true }
